PickC.Internal/Areas/Internal/Controllers/DashBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;

using PickC.Services;
using PickC.Internal.ViewModals;
using PickC.Services.DTO;
using Operation.Contract;

namespace PickC.Internal.Areas.Internal.Controllers
{
    [WebAuthFilter]
    [PickCEx]
    public class DashboardController : BaseController
    {
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            return View(await GetTripMonitorData());
        }

        [HttpGet]
        public async Task<JsonResult> GetTripMonitorInfo()
        {
            return Json(await GetTripMonitorData(), JsonRequestBehavior.AllowGet);
        }

        public async Task<List<TripMonitorVm>> GetTripMonitorData()
        {
            var tripMonitorList = await new TripMonitorService(AUTHTOKEN, p_mobileNo)
                                            .TripMonitorListAsync();

            var tripMonitorData = new List<TripMonitorVm>();
            if (tripMonitorList != null)
            {
                for (var i = 0; i < tripMonitorList.Count; i++)
                {
                    var tripMonitor = new TripMonitorVm();
                    tripMonitor.address = new Address
                    {
                        address = "",
                        lat = tripMonitorList[i].Latitude,
                        lng = tripMonitorList[i].Longitude,
                    };
                    tripMonitor.title = tripMonitorList[i].DriverID + " - " + tripMonitorList[i].TripID;

                    tripMonitorData.Add(tripMonitor);
                }
            }


            return tripMonitorData;
        }

        public async Task<ActionResult> GetDriversList()
        {
            var driverList = await new DriverService(AUTHTOKEN, p_mobileNo).DriversListAsync();
            var tripMonitor = await GetTripMonitorData();

            var driverMonitorVm = new DriverMonitorVm()
            {
                driverList = driverList,
                tripMonitorVmList = tripMonitor
            };

            return View(driverMonitorVm);
        }

        [HttpGet]
        public async Task<ActionResult> CurrentBookings(BookingDTO search)
        {
            var currentbookings = await new SearchService(AUTHTOKEN, p_mobileNo).SearchCurrentBookingAsync(search);
            var bookingSearchVM = new BookingSearchDTO();
            bookingSearchVM.booking =currentbookings;

            return View("CurrentBookings", bookingSearchVM);
        }

        [HttpPost]
        public async Task<ActionResult> CurrentBookings(BookingSearchDTO booking)
        {
            var currentbooking = await new SearchService(AUTHTOKEN, p_mobileNo).SearchBookingByDateAsync(booking);
            var bookingSearchVM = new BookingSearchDTO();
            bookingSearchVM.booking = currentbooking;

            return View("CurrentBookings", bookingSearchVM);

        }

        public async Task<JsonResult> GetDriverBySearch(bool? status=null)
        {
          
            var driverlist = await new DriverService(AUTHTOKEN, p_mobileNo).GetDriverBySearch(status);
            return Json(driverlist, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> GetDriverDetails(string id) {
            var driverlist = await new DriverService(AUTHTOKEN, p_mobileNo).DriverInfoAsync(id);
            return Json(driverlist, JsonRequestBehavior.AllowGet);
        }
    }
}

PickC.Internal/Areas/OperatorWeb/Controllers/DashBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PickC.Internal.Areas.OperatorWeb.Controllers
{
    public class DashBoardController : Controller
    {        
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
    }
}

PickC.Internal/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;

using PickC.Services;
using PickC.Internal.ViewModals;

namespace PickC.Internal.Controllers
{
    [WebAuthFilter]
    [PickCEx]
    public class DashboardController :  BaseController
    {        
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            return View(await GetTripMonitorData());
        }

        [HttpGet]
        public async Task<JsonResult> GetTripMonitorInfo()
        {
            return Json(await GetTripMonitorData(), JsonRequestBehavior.AllowGet);
        }

        public async Task<List<TripMonitorVm>> GetTripMonitorData()
        {
            var tripMonitorList = await new TripMonitorService(AUTHTOKEN, p_mobileNo)
                                            .TripMonitorListAsync();

            var tripMonitorData = new List<TripMonitorVm>();
            if(tripMonitorList != null)
            {
                for (var i = 0; i < tripMonitorList.Count; i++)
                {
                    var tripMonitor = new TripMonitorVm();
                    tripMonitor.address = new Address
                    {
                        address = "",
                        lat = tripMonitorList[i].Latitude,
                        lng = tripMonitorList[i].Longitude,
                    };
                    tripMonitor.title = tripMonitorList[i].DriverID + " - " + tripMonitorList[i].TripID;

                    tripMonitorData.Add(tripMonitor);
                }
            }
            

            return tripMonitorData;
        }
    }
}

PickC.Internal/Areas/Internal/Views/DashBoard/CurrentBookings.cshtml
@model PickC.Services.DTO.BookingSearchDTO

@using PickC.Internal.HtmlHelpers
@{
    Layout = "~/Areas/Internal/Views/Shared/_Layout.cshtml";
    WebGrid grid =
        new WebGrid(Model.booking, rowsPerPage: 10, selectionFieldName: "selectedRow", ajaxUpdateContainerId: "grid");
}

<section class="content">
    @using (Html.BeginForm("CurrentBookings", "Dashboard", FormMethod.Post, new { id = "frmCurrentBookings"}))
    {
        <div class="row">
            <ul id="myTab" class="nav nav-tabs">
                <li>
                    <a href="#tab1" data-toggle="tab" onclick="redirect();">
                        Drivers List
                    </a>
                </li>
                <li class="active">
                    <a href="#tab2" data-toggle="tab">
                        Current Bookings
                    </a>
                </li>
                @*<li>
                    <a href="#tab3" data-toggle="tab">
                        Tab3
                    </a>
                </li>*@
            </ul>
            <div id="myTabContent" class="tab-content">
                <div id="tab2" class="tab-pane fade in active">
                    <div class="row" style="margin:10px 0 0 10px;">

                        <div class="col-md-2">
                            @Html.TextBoxFor(x => x.dates.fromDate, new { @class = "form-control" })
                            @*<span class="input-group-btn">
                                    <button type="button" class="btn btn-default"><i class="fa fa-calendar" aria-hidden="true"></i></button>
                                </span>*@
                        </div>
                        <div class="col-md-2">
                            @Html.TextBoxFor(x => x.dates.toDate, new { @class = "form-control" })
                        </div>
                        <div class="col-md-2">
                            <button type="submit" id="btnSearch" class="btn btn-primary"><i class="fa fa-search"></i>Search </button>
                        </div>
                    </div>
                    <div class="box-body">
                        @if (Model != null)
                        {
                            <div class="row">

                                <div class="col-md-12">
                                    @grid.Table(
        tableStyle: "table table-hover",
        columns: grid.Columns(
             grid.Column("BookingNo", "Booking No"),
             grid.Column("BookingDate", "Booking Date"),
             grid.Column("VehicleNo", "Vehicle Number"),
             grid.Column("CargoType", "Cargo Type")
            ),
         htmlAttributes: new { id = "grid" })
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="pull-right">@grid.PagerList(mode: WebGridPagerModes.All, paginationStyle: "pagination pagination-sm")</div>
                                </div>
                            </div>

                        }
                        else
                        {
                            <div>
                                <label>No Data found...</label>
                            </div>
                        }

                    </div>

                </div>
            </div>

        </div>
    }
</section>


@section secscripts{
    <script src="@Url.Content("~/Scripts/jquery.validate.js")"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#dates_fromDate,#dates_toDate').datepicker();
            $('#frmCurrentBookings').validate({
                rules: {
                    'dates.fromDate': {
                        required: true
                    },
                    'dates.toDate': {
                        required: true
                    }
                }
            });
        });

        function redirect() {
            window.location = "@Url.Content("~/Internal/Dashboard/GetDriversList")";
        }

    </script>
}

PickC.Internal/Areas/Internal/Views/DashBoard/GetDriversList.cshtml
@model PickC.Internal.ViewModals.DriverMonitorVm

@{
    ViewBag.Title = "GetDriversList";
    Layout = "~/Areas/Internal/Views/Shared/_Layout.cshtml";
}

@section seccss{
    <style type="text/css">
        #map {
            height: 530px;
            width: 100%;
            margin: 0px;
            padding: 0px;
        }
    </style>
}
<section class="content">
    @using (Html.BeginForm())
    {

        <div class="row">
            <ul id="myTab" class="nav nav-tabs">
                <li class="active">
                    <a href="#home" data-toggle="tab">
                       Drivers List
                    </a>
                </li>
                <li>
                    <a href="#ios" data-toggle="tab" onclick="redirect();">Current Bookings</a>
                </li>

                @*<li>
                    <a href="#tab" data-toggle="tab">
                        Tab3
                    </a>
                </li>*@
            </ul>
            <div id="myTabContent" class="tab-content">
                <div class="tab-pane fade in active" id="home">
                    <div class="row map-container">

                        <div class="col-md-3">
                            <div class="search-map">
                                @*<input type="text" id="txtDriverName" placeholder="search by name" class="form-control" />*@
                                <select id="ddlSearchByStatus" class="form-control">
                                    <option value="3">All</option>
                                    <option value="true">Active</option>
                                    <option value="false">In-Active</option>
                                </select>
                            </div>
                            <div class="dr-list" id="driverList">

                                <ul class="listofvhl">
                                    @foreach (var item in Model.driverList)
                                    {
                                        <li onclick="getDriverDetails(this)" id="@item.DriverID">
                                            <img src="~/images/icon.png" class="img-circle" alt="driver" height="20" style="float:left;" />
                                            <div style="float:left;padding-left:10px;">
                                                <span style="display:block"> @item.DriverName</span>
                                                <span style="display:block"> @item.VehicleNo </span>
                                            </div>
                                            <div class="clearfix"></div>
                                            <span class="active-dr">
                                                @if (@item.Status)
                                                {
                                                    <i class="fa fa-circle text-success"></i>
                                                }
                                                else
                                                {
                                                    <i class="fa fa-circle text-danger"></i>
                                                }
                                            </span>

                                        </li>
                                    }
                                </ul>
                            </div>
                        </div>

                        <div class="col-md-9">
                            <div id="map" style="border: 1px solid rgba(255,255,255,0.15);"></div>
                        </div>

                    </div>
                </div>

            </div>
            <div id="driverDetailsModal" class="modal fade" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Driver Details</h4>
                        </div>
                        <div class="modal-body" id="driverData">


                            <img id="driverImage" src="" alt="driver" height="40" />
                            <label>Driver Name</label>
                            <div id="driverName"></div>
                            <label>LicenseNumber</label>
                            <div id="licenseNumber"></div>
                            <label>
                                Vehicle Number
                            </label>
                            <div id="vehicleNumber"></div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    }

</section>
@section secscripts{
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD7WVBL9AmhKs1QAr4x7mArA2mKZY-9nUo&v=3.exp&libraries=places&sensor=true"></script>
    <script type="text/javascript">
        var MapPoints = '@Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model.tripMonitorVmList))';
        var MY_MAPTYPE_ID = 'custom_style';
        var directionsDisplay;
        var directionsService = new google.maps.DirectionsService();
        var map;

        var hyd = new google.maps.LatLng(17.24, 78.27);
        var mapOptions = {
            zoom: 10,
            center: hyd,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };

        function initialize() {
            directionsDisplay = new google.maps.DirectionsRenderer({ suppressMarkers: true });

            if (jQuery('#map').length > 0) {

                var locations = jQuery.parseJSON(MapPoints);

                map = new google.maps.Map(document.getElementById('map'), mapOptions);

                directionsDisplay.setMap(mapOptions);

                var infowindow = new google.maps.InfoWindow();
                var flightPlanCoordinates = [];
                var bounds = new google.maps.LatLngBounds();

                for (i = 0; i < locations.length; i++) {
                   
                    marker = new google.maps.Marker({

                        position: new google.maps.LatLng(locations[i].address.lat, locations[i].address.lng),
                        map: map,
                        icon: '@Url.Content("~/images/truck.png")'
                    });
                    flightPlanCoordinates.push(marker.getPosition());
                    bounds.extend(marker.position);

                    google.maps.event.addListener(marker, 'click', (function (marker, i) {
                        return function () {
                            infowindow.setContent(locations[i]['title']);
                            infowindow.open(map, marker);
                        }
                    })(marker, i));
                }

                map.fitBounds(bounds);
                /* polyline
                    var flightPath = new google.maps.Polyline({
                        map: map,
                        path: flightPlanCoordinates,
                        strokeColor: "#FF0000",
                        strokeOpacity: 1.0,
                        strokeWeight: 2
                    }); */
                // directions service
                var start = flightPlanCoordinates[0];
                var end = flightPlanCoordinates[flightPlanCoordinates.length - 1];
                var waypts = [];
                for (var i = 1; i < flightPlanCoordinates.length - 1; i++) {
                    waypts.push({
                        location: flightPlanCoordinates[i],
                        stopover: true
                    });
                }
                //calcRoute(start, end, waypts);
            }
        }

        /*
        function calcRoute(start, end, waypts) {
            var request = {
                origin: start,
                destination: end,
                waypoints: waypts,
                optimizeWaypoints: true,
                travelMode: google.maps.TravelMode.DRIVING
            };
            directionsService.route(request, function (response, status) {
                if (status == google.maps.DirectionsStatus.OK) {
                    directionsDisplay.setDirections(response);
                    var route = response.routes[0];

                    var summaryPanel = document.getElementById('directions_panel');
                    summaryPanel.innerHTML = '';
                    for (var i = 0; i < route.legs.length; i++) {
                        var routeSegment = i + 1;
                        summaryPanel.innerHTML += '<b>Route Segment: ' + routeSegment + '</b><br>';
                        summaryPanel.innerHTML += route.legs[i].start_address + ' to ';
                        summaryPanel.innerHTML += route.legs[i].end_address + '<br>';
                        summaryPanel.innerHTML += route.legs[i].distance.text + '<br><br>';
                    }
                }
            });
        }
        */
        // google.maps.event.addDomListener(window, 'load', initialize);
        map = new google.maps.Map(document.getElementById('map'), mapOptions)

        $(function () {
            Looping();


            $('#ddlSearchByStatus').on("change", function () {
               
                $.ajax({
                    url: '@Url.Content("~/Internal/Dashboard/GetDriverBySearch")',
                    method: 'POST',
                    contentType: 'application/json',
                    dataType: 'json',
                    data: JSON.stringify({ 'status': $('#ddlSearchByStatus').val() }),
                    success: function (data) {
                       
                        $('#driverList').val();
                        var html = '';
                        $.each(data, function (key, val) {
                            html += '<ul class="listofvhl">'
                            html += '<li onclick="getDriverDetails(this)" id=' + val.DriverID + '><img src="@Url.Content( "~/images/icon.png")" class="img-circle" alt="driver" height="20" style="float:left;">';
                            html += '<div style="float:left;padding-left:10px;">';
                            html += '<span style="display:block"> ' + val.DriverName + '</span>';
                            html += '<span style="display:block"> ' + val.VehicleNo + ' </span> </div>';
                            html += '<div class="clearfix"></div>';
                            html += '<span class="active-dr">';
                            if (val.Status) {
                                html += '<i class="fa fa-circle text-success"></i>';
                            }
                            else {
                                html += '<i class="fa fa-circle text-danger"></i>';
                            }
                            html += '</span></li></ul>';



                        });

                        $('#driverList').html(html);


                    },
                    error: function (err) {
                       
                    },
                    failure: function (fail) {
                       
                    }
                });
            });
        });

        function Looping() {
            setTimeout(function () {
                var promise = GetTripMonitorData();
                $.when(promise).done(function (data) {
                    MapPoints = JSON.stringify(data);
                    initialize();
                    Looping();
                });
            }, 1000 * 60);
        }

        function GetTripMonitorData() {
            var def = $.Deferred();
            $.ajax({
                url: '@Url.Content("~/Internal/Dashboard/GetTripMonitorInfo")',
                method: 'GET',
                contentType: 'application/json',
                dataType: 'json',
                success: function (res) {
                    def.resolve(res);
                },
                error: function (err) {
                    def.reject(err);
                },
                failure: function (fail) {
                    def.reject(fail)
                }
            });
            return def.promise();
        }


        function getDriverDetails(obj) {
           
            $.ajax({
                url: '@Url.Content("~/Internal/Dashboard/GetDriverDetails")',
                method: 'POST',
                contentType: 'application/json',
                dataType: 'json',
                data: JSON.stringify({ 'id': obj.id }),
                success: function (res) {
                    $('#driverDetailsModal').modal('show');

                    var source = '@Url.Content("~/images/icon.png")';
                    $("#driverImage").attr('src', source);

                    $("#driverName").text(res.DriverName);
                    $("#licenseNumber").text(res.LicenseNo);
                    $("#vehicleNumber").text(res.VehicleNo);
                    //debugger;
                },
                error: function (err) {
                    //
                }
            });
        }


        function redirect() {
            window.location = "@Url.Content("~/Internal/Dashboard/CurrentBookings")";
        }

    </script>
}

PickC.Internal/Areas/Internal/Views/DashBoard/Index.cshtml
@model IEnumerable<PickC.Internal.ViewModals.TripMonitorVm>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Internal/Views/Shared/_Layout.cshtml";
}

@section seccss{
    <style type="text/css">
        #map {
            height: 380px;
            width: 100%;
            margin: 0px;
            padding: 0px;
        }
    </style>
}
<section class="content">
    <div class="row">
        <ul id="myTab" class="nav nav-tabs">
            <li class="active">
                <a href="@Url.Content("~/Internal/Dashboard/GetDriversList")" data-toggle="tab">
                    Tab1
              
                </a>
            </li>
            <li>
                <a href="#ios" data-toggle="tab">Tab2</a>
            </li>

            <li>
                <a href="#tab" data-toggle="tab">
                    Tab3
                </a>
            </li>
        </ul>
        <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade in active" id="home">
                <p>
                    test1
                    @Html.ActionLink("drivers", "GetDriversList", "Dashboard")
                </p>
            </div>

            <div class="tab-pane fade" id="ios">
                <p>
                    test2
                </p>
            </div>

            <div class="tab-pane fade" id="tab">
                <p>
                    test3
                </p>
            </div>
        </div>        
    </div>
    <div class="row">
        <div class="col-md-12">
            <div id="map" style="border: 1px solid rgba(255,255,255,0.15);"></div>
        </div>
    </div>
</section>